# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/minco/LvWallPadUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/minco/LvWallPadUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minco/LvWallPadUI/CMakeFiles /home/minco/LvWallPadUI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minco/LvWallPadUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyFirmware

# Build rule for target.
MyFirmware: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyFirmware
.PHONY : MyFirmware

# fast build rule for target.
MyFirmware/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/build
.PHONY : MyFirmware/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl.dir/build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_examples.dir/build.make lvgl/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_demos.dir/build.make lvgl/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

#=============================================================================
# Target rules for targets named lv_drivers

# Build rule for target.
lv_drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lv_drivers
.PHONY : lv_drivers

# fast build rule for target.
lv_drivers/fast:
	$(MAKE) $(MAKESILENT) -f lv_drivers/CMakeFiles/lv_drivers.dir/build.make lv_drivers/CMakeFiles/lv_drivers.dir/build
.PHONY : lv_drivers/fast

src/hal/app_hal.o: src/hal/app_hal.cpp.o
.PHONY : src/hal/app_hal.o

# target to build an object file
src/hal/app_hal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/hal/app_hal.cpp.o
.PHONY : src/hal/app_hal.cpp.o

src/hal/app_hal.i: src/hal/app_hal.cpp.i
.PHONY : src/hal/app_hal.i

# target to preprocess a source file
src/hal/app_hal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/hal/app_hal.cpp.i
.PHONY : src/hal/app_hal.cpp.i

src/hal/app_hal.s: src/hal/app_hal.cpp.s
.PHONY : src/hal/app_hal.s

# target to generate assembly for a file
src/hal/app_hal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/hal/app_hal.cpp.s
.PHONY : src/hal/app_hal.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/pages/main_page.o: src/ui/pages/main_page.cpp.o
.PHONY : src/ui/pages/main_page.o

# target to build an object file
src/ui/pages/main_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/pages/main_page.cpp.o
.PHONY : src/ui/pages/main_page.cpp.o

src/ui/pages/main_page.i: src/ui/pages/main_page.cpp.i
.PHONY : src/ui/pages/main_page.i

# target to preprocess a source file
src/ui/pages/main_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/pages/main_page.cpp.i
.PHONY : src/ui/pages/main_page.cpp.i

src/ui/pages/main_page.s: src/ui/pages/main_page.cpp.s
.PHONY : src/ui/pages/main_page.s

# target to generate assembly for a file
src/ui/pages/main_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/pages/main_page.cpp.s
.PHONY : src/ui/pages/main_page.cpp.s

src/ui/ui_main.o: src/ui/ui_main.cpp.o
.PHONY : src/ui/ui_main.o

# target to build an object file
src/ui/ui_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/ui_main.cpp.o
.PHONY : src/ui/ui_main.cpp.o

src/ui/ui_main.i: src/ui/ui_main.cpp.i
.PHONY : src/ui/ui_main.i

# target to preprocess a source file
src/ui/ui_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/ui_main.cpp.i
.PHONY : src/ui/ui_main.cpp.i

src/ui/ui_main.s: src/ui/ui_main.cpp.s
.PHONY : src/ui/ui_main.s

# target to generate assembly for a file
src/ui/ui_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyFirmware.dir/build.make CMakeFiles/MyFirmware.dir/src/ui/ui_main.cpp.s
.PHONY : src/ui/ui_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MyFirmware"
	@echo "... lv_drivers"
	@echo "... lvgl"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... src/hal/app_hal.o"
	@echo "... src/hal/app_hal.i"
	@echo "... src/hal/app_hal.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/pages/main_page.o"
	@echo "... src/ui/pages/main_page.i"
	@echo "... src/ui/pages/main_page.s"
	@echo "... src/ui/ui_main.o"
	@echo "... src/ui/ui_main.i"
	@echo "... src/ui/ui_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

